services:
  moni_pro:
    image: postgres:16
    container_name: postgres_primary_db
    env_file:
      - .env
    volumes:
      - postgres_primary_db:/var/lib/postgresql/data
    networks:
      - moni-pro-net
    ports:
      - "5432:5432"
    restart: always
  django_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - moni-pro-net
    depends_on:
      - moni_pro
      - redis
    restart: always
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - moni-pro-net
    restart: always
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - moni-pro-net
    depends_on:
      - redis
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A monipro worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - moni-pro-net
    depends_on:
      - redis
      - django_server
    restart: always
volumes:
  postgres_primary_db:
networks:
  moni-pro-net:
    external: true
